# Site settings
title: WildLeoKnight
tagline: Computer Science Engineer, Pixel Artist, Game Dev
description: Portfolio
image: /assets/images/image.png
url: https://github.com/meebuhs/arco
github_url: https://github.com/meebuhs
resume: false
author: Leonardo "WildLeoKnight" Lourenço
lang: en-UK

# Build settings

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap