# Site settings
title: example-title
tagline: example-tagline
description: example-description
image: /path/to/image.png
url: example-url
sidebar_main_text: example-sidebar-main-text
cover_url: example-cover-url
cover_text: example-cover-text
author: example-author
lang: en-US

# Build settings

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap